version: "3.9"

services:
  server:
    image: nginx-hw-server:0.1
    build: 
      context: ./server
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

