version: "3.9"

services:
  webapp:
    image: webapp-py-3.12.1
    build:
      context: ./app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    restart: always

  server:
    image: nginx-hw-server:0.1
    build: 
      context: ./server
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - webapp

